apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
      - name: todo-server
        image: ankitv1504/todo-server:latest
        ports:
        - containerPort: 3009
        envFrom:
        - configMapRef:
            name: todo-config
        - secretRef:
            name: todo-secret
