# todo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  DB_URL: "mongodb://testpavan:Pava&n5Y5&7AdAv@217.145.69.24:27017/"
  SESSION_KEY: "supersecretkey"
